### ISSUE TITLE
Consider ignoring environments.json in git

### ISSUE THREAD

**Issue by Simply007** [kontent-ai/migrations-boilerplate#15]
### Motivation

When you start using the environment boilerplate and set up the environment API keys, it is pretty easy to leak the keys, because this file is not ignored by default.

### Proposed solution

Ignore the `.environments.json` by default. And ensure Kontent CLI creates a `.environments.json` file by default, or ensure this i.e. as preinstall script.

**Comment by Simply007** [comment]
Kontent CLI is creating `.environments.json` automatically.

**Comment by winklertomas** [comment]
https://github.com/kontent-ai/migrations-boilerplate/pull/16
